Blog/urls.py
from django.urls import path, include

from Blog import views


urlpatterns = [
    path('', views.BlogListView.as_view(), name='blog'),
    path('<int:post_id>/', views.BlogDetailView.as_view(), name='single_post'),
    path('comment/<int:pk>/', views.BlogDetailView.as_view(), name='single_post'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('search/', views.SearchResultsListView.as_view(), name='search'),
]

Shop/urls.py
from django.urls import path
from rest_framework import routers

from Shop import views
from Shop.api import CardViewSet

from Shop.utils import global_exception_decorator as g

router = routers.DefaultRouter()
router.register('api/card', CardViewSet, 'card_product')


urlpatterns = [
    path('', views.HomeListView.as_view(), name='home'),

    path('shop/', g(views.ShopListView.as_view()), name='shop'),
    path('products/<int:product_ID>/', g(views.ProductDetailView.as_view()), name='product_detail'),
    path('review/', g(views.ProductDetailView.as_view()), name="add_review"),
    path('json-filter/', g(views.JsonFilterProductView.as_view()), name='json_filter'),

    path('cart/', g(views.CartListView.as_view()), name='cart'),
    path('add_cart/<int:product_id>', g(views.AddCart.as_view()), name='addCart'),
    path('off_cart/<int:product_id>', g(views.PopCart.as_view()), name='popCart'),
    path('del_cart/<int:product_id>', g(views.DeleteCartProduct.as_view()), name='deleteCart'),

    path('favorites/', g(views.FavoritesView.as_view()), name='favorites'),
    path('add_favorites/<int:product_id>', g(views.AddFavoritesView.as_view()), name='addFavorites'),
    path('del_favorites/<int:product_id>', g(views.DeleteFavoritesView.as_view()), name='delFavorites'),

    path('order/', g(views.OrderListView.as_view()), name='order'),
    path('default_delivery/', g(views.OrderListView.as_view()), name='choice'),
    path('order/buy', g(views.BuyView.as_view()), name='pay'),
    path('order/process/', g(views.OrderInProcessingListView.as_view()), name='orders_status')

]

urlpatterns += router.urls

e_shopper/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('', include('Shop.urls')),
    path('', include('Interactive.urls')),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n'))
]

urlpatterns += i18n_patterns(
    path('blog/', include('Blog.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('accounts/', include('allauth.urls')),
)

handler404 = 'e_shopper.handlers.ex404'
handler500 = 'e_shopper.handlers.ex500'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shop/models.py
from django.db import models
from django.db.models import CASCADE, SET_NULL, F, Sum
from django.contrib.auth.models import User
from django.urls import reverse

from decimal import Decimal

from Interactive.models import Delivery


class Category(models.Model):
    """Категории продуктов"""
    name = models.CharField("Название категории", max_length=150)
    description = models.TextField("Описание", max_length=1500, blank=True)
    slug = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Brand(models.Model):
    """Производитель продукта"""
    name = models.CharField("Название бренда", max_length=150)
    description = models.TextField("Описание", max_length=1500)
    slug = models.SlugField(max_length=160, unique=True)
    image = models.ImageField("Логотип", upload_to="media/brands/")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Бренд"
        verbose_name_plural = "Бренды"


class Card_Product(models.Model):
    """Карточка продукта"""
    product_public_ID = models.IntegerField(primary_key=False, unique=True, null=False, default=1111111)
    name = models.CharField(max_length=300)
    description = models.TextField(max_length=5000)
    price = models.DecimalField(max_digits=12, decimal_places=2)
    availability = models.BooleanField(default=True, verbose_name='hidden')
    quantity = models.PositiveIntegerField('На складе', default=0)

    NEW = 'new'
    FRESH = 'fresh'
    SECOND_HAND = 'hand'
    CONDITION_CHOICE = (
        (NEW, 'new'),
        (FRESH, 'fresh'),
        (SECOND_HAND, 'hand'),
    )
    condition = models.CharField(
        max_length=5,
        choices=CONDITION_CHOICE,
        default=FRESH,
        blank=False,
    )

    image = models.ImageField('Изображение в корзине', upload_to='media/product_icon', null=True, blank=True)
    category = models.ManyToManyField(Category, verbose_name="категории")
    brand = models.ForeignKey(Brand, verbose_name="бренды", on_delete=SET_NULL, null=True, blank=False)

    def __str__(self):
        return f'ID: {self.product_public_ID} NAME: {self.name}'

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'product_ID': self.id})

    class Meta:
        verbose_name = 'Карточка продукта'
        verbose_name_plural = 'Карточки продуктов'
        ordering = ['product_public_ID']


class ProductImage(models.Model):
    """Изображения отображаемые с карточкой товара на галерее изображений"""
    title = models.CharField("Заголовок", max_length=100, blank=True)
    description = models.TextField("Описание", max_length=2000, blank=True)
    image = models.ImageField("Фотография товара", upload_to="media/")
    product = models.ForeignKey(Card_Product, verbose_name="Продукты", on_delete=CASCADE)

    def __str__(self):
        return f'{self.title if len(self.title) > 2 else "нет заголовка"} {self.product}'

    class Meta:
        verbose_name = 'Фотография к товару'
        verbose_name_plural = 'Фотографии к товару'


class Cart(models.Model):
    """Корзина пользователя"""
    user = models.ForeignKey(User, on_delete=CASCADE)
    product = models.ForeignKey(Card_Product, on_delete=CASCADE, blank=True)
    total = models.PositiveIntegerField(default=1)

    @staticmethod
    def total_price(user_pk):
        """запрос в базу данных о стоимости всех товаров в корзине пользователя"""
        total = Cart.objects.filter(user=user_pk).aggregate(
            total_price=Sum(F('total') * F('product__price'))
        )['total_price'] or Decimal('0')
        return total

    @property
    def product_cost(self):
        """Стоимость всех идентичных товаров добавленных в корзину"""
        total = self.total * self.product.price
        return total

    def __str__(self):
        return f'{self.product}, {self.user}'

    class Meta:
        verbose_name = 'Товар в корзине'
        verbose_name_plural = 'Товары в корзине'
        unique_together = (('user', 'product'),)


class BuyProduct(models.Model):
    product_for_buy = models.ForeignKey(Card_Product, on_delete=models.SET_NULL, null=True, verbose_name='Купленные продукты')
    total = models.PositiveSmallIntegerField()


class Order(models.Model):
    """Заказ пользователя"""
    user = models.ForeignKey(User, verbose_name='Покупатель', on_delete=models.SET_NULL, null=True)
    cards = models.ManyToManyField(Card_Product)

    total = models.DecimalField(max_digits=12, decimal_places=2)

    name_first = models.CharField(max_length=350, verbose_name='Имя')
    name_last = models.CharField(max_length=350, verbose_name='Фамилия')
    phone = models.CharField(max_length=20, verbose_name='Телефон')
    address = models.TextField(verbose_name='Адрес', null=True, blank=True)
    message = models.TextField(verbose_name='Комментарий', null=True, blank=True)

    order_start = models.DateTimeField(auto_now_add=True, verbose_name='Получен')
    order_finish = models.BooleanField(verbose_name='Исполнен', default=False)

    STATUS_1 = 'created'
    STATUS_2 = 'in_progress'
    STATUS_3 = 'ready_to_receive'
    STATUS_4 = 'completed'
    STATUS_CHOICES = (
        (STATUS_1, 'Заказ получен'),
        (STATUS_2, 'Заказ обрабатывается'),
        (STATUS_3, 'Заказ готов к выдаче'),
        (STATUS_4, 'Заказ исполнен')
    )
    status = models.CharField(max_length=22, verbose_name='Статус заказа', choices=STATUS_CHOICES, default=STATUS_1)

    BUYING_SELF = 'self'
    BUYING_DELIVERY = 'delivery'
    BUYING_CHOICES = (
        (BUYING_SELF, 'Самовывоз'),
        (BUYING_DELIVERY, 'Доставка')
    )
    buying_type = models.CharField(
        max_length=22, verbose_name='Тип заказа', choices=BUYING_CHOICES, default=BUYING_SELF
    )

    def get_products_names(self):
        return ([str(obj.name) for obj in self.cards.all()])

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'


class DefaultDelivery(models.Model):
    """Отображаемый по умолчанию <адрес доставки>(Interactive.Delivery) для каждого пользователя"""
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    default = models.OneToOneField(Delivery, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.user}, {self.default}'

    class Meta:
        verbose_name = 'Адрес по умолчанию'
        verbose_name_plural = 'Адреса по умолчанию'


class RatingGrade(models.Model):
    """Отображаемые значения рейтинга (от 1 до 5)"""
    value = models.PositiveSmallIntegerField("Рейтинг", default=3)

    def __str__(self):
        return f'{self.value}'

    def get_value(self):
        return range(self.value)

    class Meta:
        verbose_name = 'Отображаемое значение рейтинга'
        verbose_name_plural = 'Отображаемые значения рейтинга'


class Review(models.Model):
    """Отзывы к продуктам"""
    name = models.CharField(max_length=150)
    email = models.EmailField()
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True, blank=True)
    update = models.DateTimeField(auto_now=True, blank=True)

    ipaddress = models.CharField('IP адрес', max_length=15)
    product = models.ForeignKey(Card_Product, verbose_name='Продукт', on_delete=CASCADE)
    grade = models.ForeignKey(RatingGrade, on_delete=CASCADE, verbose_name="оценка", blank=True)

    def __str__(self):
        return f'{self.product}, {self.name}, {self.ipaddress}'

    class Meta:
        verbose_name = 'Отзывы'
        verbose_name_plural = 'Отзывы'
        ordering = ['created']


class Favorites(models.Model):
    """Избранное пользователя"""
    user = models.ForeignKey(User, on_delete=CASCADE)
    products = models.ForeignKey(Card_Product, on_delete=CASCADE)

    def __str__(self):
        return f'{self.user}, {self.products}'

    class Meta:
        verbose_name = "Избранное"
        verbose_name_plural = "Избранные"
        unique_together = (("user", "products"),)

Blog/forms.py
from django.forms import Textarea, ModelForm, CharField

from ckeditor_uploader.widgets import CKEditorUploadingWidget

from Blog.models import Comment, News


class AddCommentForm(ModelForm):
    """Добавление комментария к новости"""

    class Meta:
        model = Comment
        fields = '__all__'
        widgets = {'text': Textarea(attrs={"id": "commentator", "placeholder": "Оставить комментарий ..."})}


class NewsAdminForm(ModelForm):
    """CKEditor"""
    description_ru = CharField(label="Описание [ru]", widget=CKEditorUploadingWidget())
    description_en = CharField(label="Description [en]", widget=CKEditorUploadingWidget())
    description_de = CharField(label="Beschreibung [de]", widget=CKEditorUploadingWidget())

    class Meta:
        model = News
        fields = '__all__'

Shop/forms.py
from django.forms import ModelForm, RadioSelect, ModelChoiceField, TextInput, EmailInput, Textarea

from Shop.models import Review, RatingGrade


class ReviewForm(ModelForm):
    """Добавление отзыва к карточке продукта"""
    grade = ModelChoiceField(
        queryset=RatingGrade.objects.all(),
        widget=RadioSelect(),
        empty_label=None,
    )

    class Meta:
        """Рендеринг формы для captcha"""
        pattern = {"class": "form-group col-md-6 form-control"}
        name_attrs = {"type": "text", "placeholder": "Ваше имя", "name": "name"} | pattern
        email_attrs = {"type": "email", "placeholder": "Адрес электронной почты"} | pattern
        text_attrs = {"name": "text", "placeholder": "Текст"} | pattern

        model = Review
        fields = ('name', 'email', 'text', 'ipaddress', 'product', 'grade')

        widgets = {
            'name':  TextInput(attrs=name_attrs),
            'email':  EmailInput(attrs=email_attrs),
            'text': Textarea(attrs=text_attrs),
        }

Blog/views.py
from django.shortcuts import redirect
from django.db.models import Q
from django.views.generic import ListView, DetailView, FormView

from Blog.models import News, Comment, User
from Blog.forms import AddCommentForm
from Blog.utils import DataMixin


class BlogListView(ListView):
    """Отображение списка всех статей с добавленной пагинацией"""
    model = News
    template_name = 'pages/blog.html'
    context_object_name = 'posts'
    paginate_by = 3
    queryset = News.objects.filter(draft=False).select_related('creator')

    def get_context_data(self, *, object_list=None, **kwargs):
        """Подсветка активной страницы"""
        context = super().get_context_data(**kwargs)
        context['title'] = 'Новостной блог'
        context['blog_selected'] = 'active'
        return context


class SearchResultsListView(BlogListView):

    def get_queryset(self):
        """Получение поискового запроса на странице с новостями и возвращение результата"""
        user_search_request = self.request.GET.get('s')
        request = self.get_results_filter(user_search_request)
        return request

    @staticmethod
    def get_results_filter(request):
        """Формирование ответа"""
        objects = News.objects.filter()
        result = objects.filter(
            Q(title__icontains=request) |
            Q(description__icontains=request)
        ).select_related('creator')
        return result


class BlogDetailView(FormView, DetailView, DataMixin):
    model = News
    template_name = 'pages/blog-single.html'
    pk_url_kwarg = 'post_id'
    context_object_name = 'single_post'
    queryset = News.objects.filter(draft=False).select_related('creator')
    form_class = AddCommentForm

    def get_success_url(self):
        return self.request.path

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = Comment.objects.filter(news=self.object).select_related('creator')
        context['count'] = context['comments'].__len__()
        context = self.check_next_and_prev_pages(context)
        return context

    def post(self, request, **kwargs):
        """Сохранение комментариев к новостям"""
        news_instance = News.objects.get(id=kwargs['pk'])
        self.save_comment(AddCommentForm(request.POST), news_instance)
        return redirect(news_instance.get_absolute_url(), permanent=True)

    def save_comment(self, form, news):
        if form.is_valid():
            creator = User.objects.get(id=self.request.user.id)
            form = form.cleaned_data
            parent = None
            if self.request.POST.get('parent', None):
                parent = Comment.objects.get(id=int(self.request.POST.get('parent')))

            comment = Comment(text=form['text'], parent=parent, news=news, creator=creator)
            comment.save()

templates/pages/base.html
{% extends 'base_main.html' %}

{% block title %} {% endblock title %}


{% block content %}

{% endblock content %}

templates/pages/favorites.html
{% extends 'pages/base.html' %}
{% load static %}
{% block title %} Избранное {% endblock title %}

{% block content %}
    <section id="cart_items">
        <div class="container">

            <!--favorites-panel-->
            {% if favorites_items|length == 0 %}
                <h2 class="title text-center">
                    <strong> Таблица избранных продуктов пуста.
                        Для добавления продукта в избранное кликните по кнопке любого
                        понравившегося товара на странице
                        <a href="{% url 'shop' %}"><u>с каталогом товаров</u></a>.
                    </strong>
                </h2>

            {% else %}
                <div class="bill-to"><p>Избранные товары:</p></div>
                <br>
                <div class="table-responsive cart_info">
                    <table class="table table-condensed">
                        <thead>
                        <tr class="cart_menu">
                            <td class="image">Item</td>
                            <td class="description"></td>
                            <td class="price">Price</td>
                            <td class="quantity">Status</td>
                            <td class="add">Add to cart</td>
                            <td class="total">Remove</td>
                            <td></td>
                        </tr>
                        </thead>
                        <tbody>

                        <!--favorites_product-->
                        {% for item in favorites_items %}
                            <tr>
                                <td class="cart_product">
                                    <a href="{{ item.products.get_absolute_url }}">
                                        <img src="{{ item.products.image.url }}"
                                             alt="{{ item.products.name }}"
                                             style="width: 100px; height: 100px"></a>
                                </td>
                                <td class="cart_description">
                                    <h4><a href="{{ item.products.get_absolute_url }}">
                                        {{ item.products.name }}</a></h4>
                                    <p>Web ID: {{ item.products.product_public_ID }}</p>
                                </td>
                                <td class="cart_price">
                                    <p>${{ item.products.price }}</p>
                                </td>
                                <td class="cart_status">
                                    <p>{{ item.products.get_condition_display|upper }}</p>
                                </td>
                                <td class="add">

                                    <form method="post" action="{% url 'addCart' item.products.id %}">
                                        {% csrf_token %}
                                        <button class="btn btn-fefault cart"><i class="fa fa-shopping-cart"></i>Add to
                                            cart
                                        </button>
                                    </form>

                                </td>
                                <td>
                                    <form method="post" action="{% url 'delFavorites' item.products.id %}">
                                        {% csrf_token %}
                                        <button class="cart_delete" style="height: 30px; width: 30px"> X</button>
                                    </form>

                                </td>
                            </tr>
                        {% endfor %}
                        <!--/favorites_product-->

                        </tbody>
                    </table>
                </div>
            {% endif %}
            <div>
            </div>
        </div>
        <hr>
        <!--/favorites-panel-->
    </section>
{% endblock content %}

templates/pages/index.html
{% extends 'pages/base.html' %}
{% load static %}
{% block title %} {{ title }} {% endblock title %}

{% block content %}


        {% include 'include/slider.html' %}

        <!--main-table-->
        <section>
            <div class="container">
                <div class="row">
                    <div class="col-sm-9 padding-right" style="width:100%;">
                        <div class="features_items">

                            {% include 'content/recommended_items.html' %}
                            {% include 'content/category_tab.html' %}

                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--/main-table-->
        <br>
        <br>

{% endblock content %}

templates/pages/product-detail.html
{% extends 'pages/base.html' %}
{% load static %}
{% block title %} {{ title }} {% endblock title %}

{% block content %}
    <script>

    </script>
    <section>
        <div class="container">
            <div class="row">
                <div class="col-sm-9 padding-right">

                    <!--product-details-->
                    <div class="product-details">
                        <div class="col-sm-5">
                            <div class="view-product">
                                <img src="{{ product_detail.image.url }}" alt="Главное изображение"/>
                            </div>
                            <div id="similar-product" class="carousel slide" data-ride="carousel">

                                <!-- wrapper-for-slides -->
                                <div class="carousel-inner">
                                    {% for page in slider %}
                                        {% if page.number > 1 %}
                                            <div class="item carousel-inner">
                                        {% else %}
                                            <div class="item active carousel-inner">
                                        {% endif %}
                                    {% for image in page.object_list %}
                                        <a href="{{ image.image.url }}" target="_blank">
                                            <img src="{{ image.image.url }}" alt="{{ image.image.title }}" width="80"
                                                 height="100">
                                        </a>
                                    {% endfor %}
                                    </div>
                                    {% endfor %}
                                    </div>
                                    <!-- /wrapper-for-slides--->

                                    <!-- Controls -->
                                    <a class="left item-control" href="#similar-product" data-slide="prev">
                                        <i class="fa fa-angle-left"></i>
                                    </a>
                                    <a class="right item-control" href="#similar-product" data-slide="next">
                                        <i class="fa fa-angle-right"></i>
                                    </a>
                                    <!--/Controls -->

                                </div>
                            </div>
                            <div class="col-sm-7">
                                <!--/product-information-->
                                <div class="product-information">
                                    {% if product_detail.condition == 'new' %}
                                        <img src="{% static 'images/product-details/new.jpg' %}" class="newarrival"
                                             alt="status-new"/>
                                    {% elif product_detail.condition == 'fresh' %}
                                        <img src="{% static 'images/product-details/fresh.png' %}" class="newarrival"
                                             alt="status-fresh"/>
                                    {% else %}
                                        <img src="{% static 'images/product-details/hand.png' %}" class="newarrival"
                                             alt="status-fresh"/>
                                    {% endif %}
                                    <h2>{{ product_detail.name }}</h2>
                                    <p>Web ID: {{ product_detail.product_public_ID }}</p>
                                    <p>
                                        {% if grade_on %}
                                            {% for star in grade_on %}
                                                <img src="{% static 'images/star-on-big.png' %}" alt="rating"/>
                                            {% endfor %}
                                            {% for star in grade_off %}
                                                <img src="{% static 'images/star-off-big.png' %}" alt="rating"/>
                                            {% endfor %}
                                        {% else %}
                                            <b> Оценок ещё нет</b>
                                        {% endif %}
                                    </p>
                                    <span>
                                    <span> $ {{ product_detail.price }}</span>
                                    <label>На складе:</label>
                                    <input type="text" value="{{ product_detail.quantity }}"/>

                            <!--cart-->
                                    <form method="post" action="{% url 'addCart' product_detail.id %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-fefault cart"><i class="fa fa-shopping-cart"></i> Добавить в корзину</button>
                                    </form>
                            <!--/cart-->

                            <!--favorites-->
                                <form method="post" action="{% url 'addFavorites' product_detail.id %}">
                                {% csrf_token %}
                                    <button type="submit" class="cart btn">
                                        <i class="fa fa-plus-square "></i> Добавить в избранное
                                    </button>
                                </form>
                            <!--/favorites-->

								</span>
                                    <p><b>Категории:</b>
                                        {{ product_detail.category.all | join:", " }}
                                    </p>
                                    <p><b>Качество товара:</b> {{ product_detail.get_condition_display|upper }}</p>
                                    <p><b>Бренд:</b> {{ product_detail.brand }}</p>
                                    <p><b>Описание:</b> {{ product_detail.description }}</p>
                                </div>
                                <!--/product-information-->
                            </div>
                        </div>
                        <!--/product-details-->

                        {% if count == 0 %}
                            <div><p><b>Рецензий ещё нет!</b></p>
                        {% else %}
                            <div><p><b>{{ count }} Рецензий </b></p>
                        {% endif %}
                        <!--reviews-->
                        <hr>
                        <div class="tab-pane fade active in" id="reviews">
                            <div class="col-sm-12">
                                <!--review-detail-->
                                {% for review in reviews %}
                                    <ul>
                                        <li><a><i class="fa fa-user"></i>{{ review.name }}</a></li>
                                        <li><a><i class="fa fa-clock-o"></i>{{ review.update|date:"G:i" }}
                                            PM</a>
                                        </li>
                                        <li><a><i class="fa fa-calendar-o"></i>{{ review.update|date:"d-F-Y" }}
                                        </a>
                                        </li>
                                    </ul>
                                    <p>{{ review.text }}</p>
                                    <br>
                                    {% for star in review.grade.get_value %}
                                        <img src="{% static 'images/star-on-big.png' %}" alt="rating"/>
                                    {% endfor %}
                                    <hr>
                                {% endfor %}
                                <!--/review-detail-->

                                <!--contact-form-->
                                <div>
                                    {% if count == 0 %}
                                        <div><p><b>Оставить первый отзыв:</b></p>
                                    {% else %}
                                        <div><p><b>Написать отзыв:</b></p>
                                    {% endif %}

                                    <!--form-->
                                    <form action="{% url 'add_review' %}" method="post" name="review">
                                        {% csrf_token %}
                                        <input type="hidden" value="{{ product_detail.id }}" name="product">
                                        <input type="hidden" value="#" name="ipaddress">
                                        <span>{{ form.name.errors }} {{ form.email.errors }}</span>
                                        <span>{{ form.name }} {{ form.email }}</span>
                                        {{ form.text }}
                                        <b>Оценить: </b>
                                        {% for k, v in form.fields.grade.choices %}
                                            <input required id="review{{ v }}" type="radio" name="grade"
                                                   value="{{ k }}">
                                            <label for="review{{ v }}">{{ k }}</label>
                                        {% endfor %}
                                        <button class="btn btn-default pull-right" type="submit" name="submit">
                                            Submit
                                        </button>
                                    </form>
                                    <!--/form-->

                                    </div>
                                    </div>
                                    <br><br><br>
                                </div>
                                <!--/contact-form-->
                                <br>
                                <br>
                                <br>
                            </div>
                        </div>
                        </div>
                        </div>
                        <!--/reviews-->
                    </div>
                </div>
            </div>
    </section>
{% endblock content %}