Blog/urls.py
from django.urls import path, include

from Blog import views


urlpatterns = [
    path('', views.BlogListView.as_view(), name='blog'),
    path('<int:post_id>/', views.BlogDetailView.as_view(), name='single_post'),
    path('comment/<int:pk>/', views.BlogDetailView.as_view(), name='single_post'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('search/', views.SearchResultsListView.as_view(), name='search'),
]

e_shopper/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('', include('Shop.urls')),
    path('', include('Interactive.urls')),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n'))
]

urlpatterns += i18n_patterns(
    path('blog/', include('Blog.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('accounts/', include('allauth.urls')),
)

handler404 = 'e_shopper.handlers.ex404'
handler500 = 'e_shopper.handlers.ex500'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shop/models.py
from django.db import models
from django.db.models import CASCADE, SET_NULL, F, Sum
from django.contrib.auth.models import User
from django.urls import reverse

from decimal import Decimal

from Interactive.models import Delivery


class Category(models.Model):
    """Категории продуктов"""
    name = models.CharField("Название категории", max_length=150)
    description = models.TextField("Описание", max_length=1500, blank=True)
    slug = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Brand(models.Model):
    """Производитель продукта"""
    name = models.CharField("Название бренда", max_length=150)
    description = models.TextField("Описание", max_length=1500)
    slug = models.SlugField(max_length=160, unique=True)
    image = models.ImageField("Логотип", upload_to="media/brands/")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Бренд"
        verbose_name_plural = "Бренды"


class Card_Product(models.Model):
    """Карточка продукта"""
    product_public_ID = models.IntegerField(primary_key=False, unique=True, null=False, default=1111111)
    name = models.CharField(max_length=300)
    description = models.TextField(max_length=5000)
    price = models.DecimalField(max_digits=12, decimal_places=2)
    availability = models.BooleanField(default=True, verbose_name='hidden')
    quantity = models.PositiveIntegerField('На складе', default=0)

    NEW = 'new'
    FRESH = 'fresh'
    SECOND_HAND = 'hand'
    CONDITION_CHOICE = (
        (NEW, 'new'),
        (FRESH, 'fresh'),
        (SECOND_HAND, 'hand'),
    )
    condition = models.CharField(
        max_length=5,
        choices=CONDITION_CHOICE,
        default=FRESH,
        blank=False,
    )

    image = models.ImageField('Изображение в корзине', upload_to='media/product_icon', null=True, blank=True)
    category = models.ManyToManyField(Category, verbose_name="категории")
    brand = models.ForeignKey(Brand, verbose_name="бренды", on_delete=SET_NULL, null=True, blank=False)

    def __str__(self):
        return f'ID: {self.product_public_ID} NAME: {self.name}'

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'product_ID': self.id})

    class Meta:
        verbose_name = 'Карточка продукта'
        verbose_name_plural = 'Карточки продуктов'
        ordering = ['product_public_ID']


class ProductImage(models.Model):
    """Изображения отображаемые с карточкой товара на галерее изображений"""
    title = models.CharField("Заголовок", max_length=100, blank=True)
    description = models.TextField("Описание", max_length=2000, blank=True)
    image = models.ImageField("Фотография товара", upload_to="media/")
    product = models.ForeignKey(Card_Product, verbose_name="Продукты", on_delete=CASCADE)

    def __str__(self):
        return f'{self.title if len(self.title) > 2 else "нет заголовка"} {self.product}'

    class Meta:
        verbose_name = 'Фотография к товару'
        verbose_name_plural = 'Фотографии к товару'


class Cart(models.Model):
    """Корзина пользователя"""
    user = models.ForeignKey(User, on_delete=CASCADE)
    product = models.ForeignKey(Card_Product, on_delete=CASCADE, blank=True)
    total = models.PositiveIntegerField(default=1)

    @staticmethod
    def total_price(user_pk):
        """запрос в базу данных о стоимости всех товаров в корзине пользователя"""
        total = Cart.objects.filter(user=user_pk).aggregate(
            total_price=Sum(F('total') * F('product__price'))
        )['total_price'] or Decimal('0')
        return total

    @property
    def product_cost(self):
        """Стоимость всех идентичных товаров добавленных в корзину"""
        total = self.total * self.product.price
        return total

    def __str__(self):
        return f'{self.product}, {self.user}'

    class Meta:
        verbose_name = 'Товар в корзине'
        verbose_name_plural = 'Товары в корзине'
        unique_together = (('user', 'product'),)


class BuyProduct(models.Model):
    product_for_buy = models.ForeignKey(Card_Product, on_delete=models.SET_NULL, null=True, verbose_name='Купленные продукты')
    total = models.PositiveSmallIntegerField()


class Order(models.Model):
    """Заказ пользователя"""
    user = models.ForeignKey(User, verbose_name='Покупатель', on_delete=models.SET_NULL, null=True)
    cards = models.ManyToManyField(Card_Product)

    total = models.DecimalField(max_digits=12, decimal_places=2)

    name_first = models.CharField(max_length=350, verbose_name='Имя')
    name_last = models.CharField(max_length=350, verbose_name='Фамилия')
    phone = models.CharField(max_length=20, verbose_name='Телефон')
    address = models.TextField(verbose_name='Адрес', null=True, blank=True)
    message = models.TextField(verbose_name='Комментарий', null=True, blank=True)

    order_start = models.DateTimeField(auto_now_add=True, verbose_name='Получен')
    order_finish = models.BooleanField(verbose_name='Исполнен', default=False)

    STATUS_1 = 'created'
    STATUS_2 = 'in_progress'
    STATUS_3 = 'ready_to_receive'
    STATUS_4 = 'completed'
    STATUS_CHOICES = (
        (STATUS_1, 'Заказ получен'),
        (STATUS_2, 'Заказ обрабатывается'),
        (STATUS_3, 'Заказ готов к выдаче'),
        (STATUS_4, 'Заказ исполнен')
    )
    status = models.CharField(max_length=22, verbose_name='Статус заказа', choices=STATUS_CHOICES, default=STATUS_1)

    BUYING_SELF = 'self'
    BUYING_DELIVERY = 'delivery'
    BUYING_CHOICES = (
        (BUYING_SELF, 'Самовывоз'),
        (BUYING_DELIVERY, 'Доставка')
    )
    buying_type = models.CharField(
        max_length=22, verbose_name='Тип заказа', choices=BUYING_CHOICES, default=BUYING_SELF
    )

    def get_products_names(self):
        return ([str(obj.name) for obj in self.cards.all()])

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'


class DefaultDelivery(models.Model):
    """Отображаемый по умолчанию <адрес доставки>(Interactive.Delivery) для каждого пользователя"""
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    default = models.OneToOneField(Delivery, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.user}, {self.default}'

    class Meta:
        verbose_name = 'Адрес по умолчанию'
        verbose_name_plural = 'Адреса по умолчанию'


class RatingGrade(models.Model):
    """Отображаемые значения рейтинга (от 1 до 5)"""
    value = models.PositiveSmallIntegerField("Рейтинг", default=3)

    def __str__(self):
        return f'{self.value}'

    def get_value(self):
        return range(self.value)

    class Meta:
        verbose_name = 'Отображаемое значение рейтинга'
        verbose_name_plural = 'Отображаемые значения рейтинга'


class Review(models.Model):
    """Отзывы к продуктам"""
    name = models.CharField(max_length=150)
    email = models.EmailField()
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True, blank=True)
    update = models.DateTimeField(auto_now=True, blank=True)

    ipaddress = models.CharField('IP адрес', max_length=15)
    product = models.ForeignKey(Card_Product, verbose_name='Продукт', on_delete=CASCADE)
    grade = models.ForeignKey(RatingGrade, on_delete=CASCADE, verbose_name="оценка", blank=True)

    def __str__(self):
        return f'{self.product}, {self.name}, {self.ipaddress}'

    class Meta:
        verbose_name = 'Отзывы'
        verbose_name_plural = 'Отзывы'
        ordering = ['created']


class Favorites(models.Model):
    """Избранное пользователя"""
    user = models.ForeignKey(User, on_delete=CASCADE)
    products = models.ForeignKey(Card_Product, on_delete=CASCADE)

    def __str__(self):
        return f'{self.user}, {self.products}'

    class Meta:
        verbose_name = "Избранное"
        verbose_name_plural = "Избранные"
        unique_together = (("user", "products"),)

templates/content/category_tab.html
{% load static float_tags  %}
<div class="category-tab">
    <div class="col-sm-12">
        <ul class="nav nav-tabs">

            {% for category in categories %}
                {% if category == categories|first %}
                    <li class="active">
                        {% else %}
                    <li>
                {% endif %}
            <a href="#{{ category.id }}" data-toggle="tab">{{ category.name }}</a></li>
            {% endfor %}

        </ul>
    </div>

    <!--RECOMMENDED head-->
    <div class="tab-content">
        {% for category in categories %}
            {% if category == categories|first %}
                <div class="tab-pane fade active in" id="{{ category.id }}">
            {% else %}
                <div class="tab-pane fade in" id="{{ category.id }}">
            {% endif %}

        <!--category_tab-->
        {% for item in category.card_product_set.all|slice:":4" %}
            {% if item.availability == False %}
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <a href="{{ item.get_absolute_url }}" target="_blank"></a>
                                {% if item.image %}
                                    <a href="{{ item.get_absolute_url }}" target="_blank"><img src="{{ item.image.url }}" alt="{{ item.name }}"/></a>
                                {% else %}
                                    <b style="color:red"> Изображение не загружено</b>
                                {% endif %}
                            <h2>${{ item.price|formatted_float }}</h2>
                            <p><a href="{{ item.get_absolute_url }}"> {{ item.name }}</a></p>

                            <!-- add to card -->
                            <form method="post" action="{% url 'addCart' item.id %}">
                                {% csrf_token %}
                                <button class="btn btn-fefault cart" style="margin-right: 20px;">
                                    <i class="fa fa-shopping-cart">
                                    </i> Добавить в корзину
                                </button>
                            </form>
                        </div>
                    </div>

                    {% if item.condition == 'new' %}
                        <img src="{% static 'images/home/new.png' %}" class="new" alt="status-new"/>
                    {% elif item.condition == 'fresh' %}
                        <img src="{% static 'images/home/fresh.png' %}" class="new" alt="status-fresh"/>
                    {% else %}
                        <img src="{% static 'images/home/hand.png' %}" class="new" alt="status-hand"/>
                    {% endif %}

                <div class="productinfo text-center">
                    <div class="choose">
                        <ul class="nav nav-pills nav-justified" style="background-color: white; border: 0px">
                            <div class="justify-center btn " style="margin:auto; margin-right: 20px;">
                                <form method="post" action="{% url 'addFavorites' item.id %}">
                                    {% csrf_token %}
                                    <li>
                                        <button type="submit" class="cart btn">
                                            <i class="fa fa-plus-square "></i> Добавить в избранное
                                        </button>
                                    </li>
                                </form>
                            </div>
                        </ul>
                    </div>
                </div>
            </div>
            </div>
            {% endif %}

        {% endfor %}
        <!--/category_tab-->


        </div>
        {% endfor %}

        <!--/RECOMMENDED head-->
        </div>
    </div>
</div>
<!--/category-tab-->

templates/content/features_items.html
{% load static float_tags %}
<!--features-items-->
<h2 class="title text-center">Представленные продукты</h2>

<div class="ajax">
    <div class="row-scripts">
        {% for product in products %}
            <div class="col-sm-4">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <a href="../products/{{ product.id }}" target="_blank">
                                {% if product.image %}
                                    <img src="../media/{{ product.image }}" alt="{{ product.name }}"/></a>
                                {% else %}
                                    <b style="color:red"> Изображение не загружено</b>
                                {% endif %}
                            <h2>${{ product.price|formatted_float }}</h2>
                            <p><a href="../products/{{ product.id }}" target="_blank"> {{ product.name }}</a></p>
                            <div style="margin-right: 20px;">
                                <a href="../products/{{ product.id }}" target="_blank">
                                    <button class="btn btn-fefault cart"><i class="fa fa-arrow-circle-right">
                                    </i> Подробнее о продукте
                                    </button>
                                </a>
                            </div>
                        </div>
                        <div>
                            <img src="../../static/images/home/{{ product.condition }}.png" class="new" alt="status-new"/>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
</div>
<!--features-items-->

templates/content/recommended_items.html
{% load static float_tags %}
<!--recommended-items-->
<div class="recommended_items">
    <h2 class="title text-center">рекомендуемые товары</h2>
    <div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">

            <!-- slide-one-->
            <div class="item active">
                {% for product in recommended_item %}
                    <div class="col-sm-4">
                        <div class="product-image-wrapper">
                            <div class="single-products">
                                <div class="productinfo text-center">
                                    <a href="products/{{ product.id }}" target="_blank">
                                        {% if product.image %}
                                            <img src="media/{{ product.image }}" alt="{{ product.name }}"/></a>
                                        {% else %}
                                            <b style="color:red"> Изображение не загружено</b>
                                        {% endif %}
                                    <h2>${{ product.price|formatted_float }}</h2>
                                    <p><a href="products/{{ product.id }}" target="_blank"> {{ product.name }}</a></p>

                                    <!-- add to card -->
                                    <form method="post" action="{% url 'addCart' product.id %}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-fefault cart" style="margin-right: 20px;">
                                            <i class="fa fa-shopping-cart">
                                            </i> Добавить в корзину
                                        </button>
                                    </form>
                                </div>
                            </div>

                        {% if product.condition == 'new' %}
                            <img src="{% static 'images/home/new.png' %}" class="new" alt="status-fresh"/>
                        {% elif product.condition == 'fresh' %}
                            <img src="{% static 'images/home/fresh.png' %}" class="new" alt="status-fresh"/>
                        {% else %}
                            <img src="{% static 'images/home/hand.png' %}" class="new" alt="status-hand"/>
                        {% endif %}


                <div class="productinfo text-center">
                    <div class="choose">
                        <ul class="nav nav-pills nav-justified" style="">
                            <div class="justify-center btn " style="margin:auto; margin-right: 20px;">
                                <form method="post" action="{% url 'addFavorites' product.id %}">
                                    {% csrf_token %}
                                    <li>
                                        <button type="submit" class="cart btn">
                                            <i class="fa fa-plus-square "></i> Добавить в избранное
                                        </button>
                                    </li>
                                </form>
                            </div>
                        </ul>
                    </div>
                </div>
            </div>
            </div>
                {% endfor %}
            </div>
            <!--/slide-one-->

            <!-- slide-two-->
            {% for rec in recommended_next_items %}
                <div class="item">

                    {% for product in rec %}
                        <div class="col-sm-4">
                            <div class="product-image-wrapper">
                                <div class="single-products">
                                    <div class="productinfo text-center">
                                        <a href="../products/{{ product.id }}" target="_blank">
                                            <img src="media/{{ product.image }}" alt="{{ product.name }}"/></a>
                                        <h2>${{ product.price|formatted_float }}</h2>
                                        <p><a href="products/{{ product.id }}" target="_blank"> {{ product.name }}</a></p>

                                        <!-- add to card -->
                                        <form method="post" action="{% url 'addCart' product.id %}">
                                            {% csrf_token %}
                                            <button class="btn btn-fefault cart" style="margin-right: 20px;">
                                                <i class="fa fa-shopping-cart"></i> Добавить в корзину
                                            </button>
                                        </form>
                                    </div>
                                </div>

                            {% if product.condition == 'new' %}
                                <img src="{% static 'images/home/new.png' %}" class="new" alt="status-new"/>
                            {% elif product.condition == 'fresh' %}
                                <img src="{% static 'images/home/fresh.png' %}" class="new" alt="status-fresh"/>
                            {% else %}
                                <img src="{% static 'images/home/hand.png' %}" class="new" alt="status-hand"/>
                            {% endif %}

                        <div class="productinfo text-center">
                    <div class="choose">
                        <ul class="nav nav-pills nav-justified" style="">
                            <div class="justify-center btn " style="margin:auto; margin-right: 20px;">
                                <form method="post" action="{% url 'addFavorites' product.id %}">
                                    {% csrf_token %}
                                    <li>
                                        <button type="submit" class="cart btn">
                                            <i class="fa fa-plus-square "></i> Добавить в избранное
                                        </button>
                                    </li>
                                </form>
                            </div>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
                    {% endfor %}
                </div>
            {% endfor %}
            <!--/slide-two-->

        </div>
        <a class="left recommended-item-control" href="#recommended-item-carousel" data-slide="prev">
            <i class="fa fa-angle-left"></i>
        </a>
        <a class="right recommended-item-control" href="#recommended-item-carousel" data-slide="next">
            <i class="fa fa-angle-right"></i>
        </a>
    </div>
</div>
<!--/recommended-items-->